
-- 📦 DDL – Comandos de definição (Oracle)

-- 🔸 CREATE TABLE

-- CREATE TABLE T_EXEMPLO (
--     ID NUMBER(5),
--     NOME VARCHAR2(50)
-- );



-- ⸻

-- 🔐 CONSTRAINTS (PK, UNIQUE, CHECK, FK)

-- ALTER TABLE T_EXEMPLO ADD CONSTRAINT pk_exemplo PRIMARY KEY (ID);
-- ALTER TABLE T_EXEMPLO ADD CONSTRAINT un_exemplo UNIQUE (NOME);
-- ALTER TABLE T_EXEMPLO ADD CONSTRAINT ck_exemplo CHECK (ID > 0);
-- ALTER TABLE T_EXEMPLO ADD CONSTRAINT fk_exemplo FOREIGN KEY (ID_DEP) REFERENCES OUTRA_TABELA(ID);



-- ⸻

-- ➕ ALTER TABLE – Adicionar colunas

-- ALTER TABLE T_EXEMPLO ADD (COL1 VARCHAR2(20), COL2 NUMBER(5));



-- ⸻

-- 🛠️ ALTER TABLE – Modificar colunas

-- ALTER TABLE T_EXEMPLO MODIFY COL2 NUMBER(10);
-- ALTER TABLE T_EXEMPLO MODIFY COL2 NOT NULL;
-- ALTER TABLE T_EXEMPLO MODIFY COL2 NULL;



-- ⸻

-- ✏️ Renomear coluna ou tabela

-- ALTER TABLE T_EXEMPLO RENAME COLUMN antigo TO novo;
-- ALTER TABLE T_EXEMPLO RENAME TO NOVO_NOME;



-- ⸻

-- 💬 Comentários

-- COMMENT ON COLUMN T_EXEMPLO.COL1 IS 'Descrição da coluna';
-- COMMENT ON TABLE T_EXEMPLO IS 'Descrição da tabela';



-- ⸻

-- 📌 DEFAULT (Valor Padrão)

-- Ao criar a tabela:

-- CREATE TABLE T_EXEMPLO (
--     ID NUMBER DEFAULT 0,
--     STATUS VARCHAR2(10) DEFAULT 'ativo',
--     DT_CADASTRO DATE DEFAULT SYSDATE
-- );

-- Para alterar:

-- ALTER TABLE T_EXEMPLO MODIFY STATUS DEFAULT 'ativo';
-- ALTER TABLE T_EXEMPLO MODIFY STATUS DEFAULT NULL; -- remove

-- ✅ Obs: Oracle usa SYSDATE para data/hora atual.

-- ⸻

-- 🗑️ DROP – Remoções

-- Tabela com constraints:

-- DROP TABLE T_EXEMPLO CASCADE CONSTRAINTS;

-- Constraint:

-- ALTER TABLE T_EXEMPLO DROP CONSTRAINT nome_constraint;

-- Remover várias colunas:

-- ALTER TABLE T_EXEMPLO DROP (COL1, COL2);



-- ⸻

-- 🔁 SEQUENCE

-- CREATE SEQUENCE SQ_EXEMPLO
-- START WITH 1
-- INCREMENT BY 1
-- MAXVALUE 9999
-- CACHE 10
-- NOCYCLE;

-- Usando com INSERT:

-- INSERT INTO T_EXEMPLO (ID, NOME)
-- VALUES (SQ_EXEMPLO.NEXTVAL, 'João');

-- -- Pegar último valor usado (na sessão):
-- SELECT SQ_EXEMPLO.CURRVAL FROM DUAL;

-- Alterar sequência:

-- ALTER SEQUENCE SQ_EXEMPLO
-- INCREMENT BY 2
-- MAXVALUE 10000
-- NOCACHE
-- NOCYCLE;



-- ⸻

-- 🆔 IDENTITY (a partir do Oracle 12c)

-- CREATE TABLE T_USUARIOS (
--     ID_USER NUMBER GENERATED ALWAYS AS IDENTITY,
--     NOME_USER VARCHAR2(10) NOT NULL
-- );

-- 🧠 Use GENERATED BY DEFAULT AS IDENTITY para permitir sobrescrever o valor se quiser.

-- ⸻

-- 🔄 Resumo DML

-- -- INSERT
-- INSERT INTO T_EXEMPLO (ID, NOME) VALUES (1, 'TESTE');

-- -- SELECT
-- SELECT * FROM T_EXEMPLO;

-- -- UPDATE
-- UPDATE T_EXEMPLO SET NOME = 'ALTERADO' WHERE ID = 1;

-- -- DELETE
-- DELETE FROM T_EXEMPLO WHERE ID = 1;