
-- -- 📦 CREATE TABLE

/*
    CREATE TABLE T_EXEMPLO (
     ID INTEGER,
     NOME VARCHAR(50)
    ); 
 */

---- 🔐 CONSTRAINTS

    -- Chave Primária
        -- ALTER TABLE T_EXEMPLO ADD CONSTRAINT pk_exemplo PRIMARY KEY (ID);

    -- Valor Único
        -- ALTER TABLE T_EXEMPLO ADD CONSTRAINT un_exemplo UNIQUE (NOME);

    -- Validação
        -- ALTER TABLE T_EXEMPLO ADD CONSTRAINT ck_exemplo CHECK (ID > 0);

    -- Chave Estrangeira
        -- ALTER TABLE T_EXEMPLO ADD CONSTRAINT fk_exemplo FOREIGN KEY (ID_DEP) REFERENCES OUTRA_TABELA(ID);


---- ➕ ALTER TABLE - Adicionar Colunas
    -- ALTER TABLE T_EXEMPLO ADD COLUMN COL1 VARCHAR(20), ADD COLUMN COL2 INTEGER;


---- 🛠️ ALTER TABLE - Modificar Colunas
    -- ALTER TABLE T_EXEMPLO ALTER COLUMN COL2 TYPE NUMERIC(10);
    -- ALTER TABLE T_EXEMPLO ALTER COLUMN COL2 SET NOT NULL;
    -- ALTER TABLE T_EXEMPLO ALTER COLUMN COL2 DROP NOT NULL;


---- ✏️ Renomear

    -- -- Renomear coluna:
        -- ALTER TABLE T_EXEMPLO RENAME COLUMN COL1 TO NOVO_COL;

    -- -- Renomear tabela:
        -- ALTER TABLE T_EXEMPLO RENAME TO NOVA_TABELA;


---- 💬 Comentários

    -- COMMENT ON COLUMN T_EXEMPLO.COL1 IS 'Descricao da coluna';
    -- COMMENT ON TABLE T_EXEMPLO IS 'Descricao da tabela';


---- 📌 DEFAULT
    /* 
    CREATE TABLE T_EXEMPLO_DEFAULT (
        ID INTEGER DEFAULT 0,
        STATUS VARCHAR(10) DEFAULT 'ativo',
        DT_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
     ); 
     */

    ---- Adicionar ou Remover DEFAULT
    -- ALTER TABLE T_EXEMPLO_DEFAULT ALTER COLUMN STATUS SET DEFAULT 'ativo';
    -- ALTER TABLE T_EXEMPLO_DEFAULT ALTER COLUMN STATUS DROP DEFAULT;


---- 🗑️ DROP

    ---- Apagar tabela com dependências:
        -- DROP TABLE IF EXISTS T_EXEMPLO CASCADE;

    ---- Apagar constraint:
        -- ALTER TABLE T_EXEMPLO DROP CONSTRAINT nome_constraint;

    ---- Apagar várias colunas:
        -- ALTER TABLE T_EXEMPLO
        -- DROP COLUMN COL1,
        -- DROP COLUMN COL2;


---- 🔢 SEQUENCES

---- Criar sequence:
    -- CREATE SEQUENCE SQ_EXEMPLO
    -- START 1 INCREMENT 1 MAXVALUE 1000
    -- CACHE 1
    -- NO CYCLE;

---- Usar sequence em insert:
    -- INSERT INTO T_EXEMPLO (ID, NOME) VALUES (nextval('SQ_EXEMPLO'), 'Fulano');

---- Obter valor atual:
    -- SELECT currval('SQ_EXEMPLO');

---- Alterar sequence:
    -- ALTER SEQUENCE SQ_EXEMPLO INCREMENT BY 2 MAXVALUE 5000 RESTART WITH 10;


---- 🆔 GENERATED IDENTITY

    ---- Criar tabela com ID gerado automaticamente:
        /*
        CREATE TABLE T_USUARIOS (
             ID_USER INT GENERATED ALWAYS AS IDENTITY NOT NULL,
             NOME_USER VARCHAR(10) NOT NULL
         );
        */

---- Opções:
    -- GENERATED ALWAYS AS IDENTITY: PostgreSQL sempre gera.
    -- GENERATED BY DEFAULT AS IDENTITY: você pode inserir valores se quiser.

---- Inserir:
    -- INSERT INTO T_USUARIOS (NOME_USER) VALUES ('Joao');


-- -- 💡 RESUMO FINAL

    ---- DDL: CREATE, ALTER, DROP, COMMENT, CONSTRAINTS, SEQUENCE, IDENTITY
    ---- DML: INSERT com DEFAULT, NEXTVAL, CURRVAL
    ---- PostgreSQL usa CURRENT_TIMESTAMP ao invés de SYSDATE
    ---- Não tem CASCADE CONSTRAINTS, apenas CASCADE
    ---- Sempre usa ALTER COLUMN para mudar propriedades de colunas

